### ISSUE TITLE
Change TokenIcon logic

### ISSUE THREAD

**Issue by adrifdez** [hermeznetwork/bridge-ui#43]
## Rationale

Avoid filter inside TokenIcon and render directly the icon from Token

**Comment by amonsosanz** [comment]
I've been thinking about this and changed my mind since our last conversation. Instead of making this component receive a `Token`, I think it should be a generic way to render icons and receive only a URL. When we want to render an icon from a `Token` the user of this component will have access to the URL and can provide it. Like this, we can use this component for any case that requires rendering an icon from a URL.

```typescript
import { FC } from "react";
import iconStyles from "src/views/shared/token-icon/token-icon.styles";

interface IconProps {
  url: string;
  className?: string;
  size?: number;
}

const Icon: FC<IconProps> = ({ url, className, size }) => {
  const classes = iconStyles(size || 16);
  return <img src={url} className={`${classes.icon} ${className ? className : ""}`} />;
};

export default Icon;
```

**Comment by amonsosanz** [comment]
This has been partially implemented in this PR: https://github.com/hermeznetwork/bridge-ui/pull/45/files#diff-15f75f487886e33745ca858635ea98654304e84df6ccd847bde51cc94e2ee33eR71
